name: Set up RDP with Serveo

on: [push]

jobs:
  setup-rdp:
    runs-on: windows-2022

    steps:
    - name: Enable RDP and configure firewall
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Set password for runneradmin
      run: |
        $password = ConvertTo-SecureString "ComplexP@ssw0rd2024!" -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $password

    - name: Install OpenSSH client
      run: Add-WindowsCapability -Online -Name OpenSSH.Client*

    - name: Attempt to connect to Serveo
      run: |
        $maxAttempts = 5
        $attempt = 0
        $connected = $false

        while (-not $connected -and $attempt -lt $maxAttempts) {
          $attempt++
          Write-Host "Attempt $($attempt) to connect to Serveo"
          ssh -o "StrictHostKeyChecking no" -R chakka:3389:localhost:3389 serveo.net > serveo_output.txt 2>&1 &
          Start-Sleep -Seconds 10

          $serveoUrl = (Select-String -Path serveo_output.txt -Pattern "Forwarding TCP traffic from [^ ]+").Line
          if ($serveoUrl) {
            $connected = $true
            Write-Host "Connected to Serveo. RDP Connection URL: $serveoUrl"
            echo "RDP Connection URL: $serveoUrl" | Out-File -FilePath rdp_connection.txt
          } else {
            Write-Host "Connection to Serveo failed, retrying..."
          }
        }

        if (!$connected) {
          Write-Host "Failed to connect to Serveo after $maxAttempts attempts"
          echo "Failed to connect to Serveo" | Out-File -FilePath rdp_connection.txt
        }  

      - name: Print Serveo output for debugging
        run: Get-Content serveo_output.txt

    - name: Print RDP Connection URL
      run: type rdp_connection.txt
