name: Set up RDP with LocalXpose

on: [push]

jobs:
  setup-rdp:
    runs-on: windows-2022

    steps:
    - name: Enable RDP and configure firewall
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Set password for runneradmin
      run: |
        $password = ConvertTo-SecureString "ComplexP@ssw0rd2024!" -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $password

    - name: Install OpenSSH client
      run: Add-WindowsCapability -Online -Name OpenSSH.Client*

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; 
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; 
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install LocalXpose using Chocolatey
      run: choco install localxpose -y

    - name: Authenticate with LocalXpose
      run: |
        "0ndwTzUcWCwXuND835Y35ZvqHUbEgriizjpaUCvB" | loclx account login

    - name: Create RDP tunnel with LocalXpose
      run: |
        Start-Process -FilePath "loclx.exe" -ArgumentList "tunnel tcp --to localhost:3389" -NoNewWindow -PassThru
        Start-Sleep -Seconds 10

    - name: Retrieve and print LocalXpose tunnel URL
      run: |
        $tunnelInfo = loclx tunnels
        $tunnelUrl = $tunnelInfo | Select-String -Pattern "https://.*"
        if ($tunnelUrl) {
          Write-Host "RDP Connection URL: $tunnelUrl"
          echo "RDP Connection URL: $tunnelUrl" | Out-File -FilePath rdp_connection.txt
        } else {
          Write-Host "Failed to create LocalXpose tunnel"
          echo "Failed to create LocalXpose tunnel" | Out-File -FilePath rdp_connection.txt
        }

    - name: Print RDP Connection URL
      run: type rdp_connection.txt
