name: RDP Tunnel Setup with PageKite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PageKite
      run: |
        sudo apt-get update
        sudo apt-get install -y pagekite

    - name: Configure and Run PageKite
      run: |
        pagekite.py 3389 ${KITE_NAME}.pagekite.me:3389
      env:
        KITE_NAME: ${{ secrets.KITE_NAME }}
        KITE_SECRET: ${{ secrets.KITE_SECRET }}

    - name: Keep Workflow Running
      run: sleep infinity
