name: RDP Tunnel Setup with PageKite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PageKite
      run: |
        pip install pagekite

    - name: Configure and Run PageKite
      run: |
        pagekite.py 3389 ${env:KITE_NAME}.pagekite.me:3389
      env:
        KITE_NAME: ${{ secrets.KITE_NAME }}
        KITE_SECRET: ${{ secrets.KITE_SECRET }}

    - name: Keep Workflow Running
      run: |
        timeout /t -1
