name: RDP Tunnel Setup with PageKite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download PageKite Script
      run: |
        curl -O https://pagekite.net/pk/pagekite.py

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Use Python 3.9 to ensure compatibility with imp module

    - name: Run PageKite
      run: |
        python pagekite.py 3389 ${{ secrets.KITE_NAME }}.pagekite.me:3389 ${{ secrets.KITE_SECRET }}

    - name: Keep Workflow Running
      run: |
        timeout /t -1
